### ISSUE TITLE
Focus is lost on home screen

### ISSUE THREAD

**Issue by pannal** [plexinc/plex-for-kodi#169]
I'm not sure after which action this happened, but suddenly no item had focus on the P4K home screen and I had to press up to activate the top menu, then I was able to normally use the home screen again.

Found this:
```
22:27:01.953 T:4080611920   ERROR: Control 400 in window 13002 has been asked to focus, but it can't
22:27:02.184 T:3657958144   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: tuple.index(x): x not in tuple
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/script.plex/lib/windows/home.py", line 444, in onClick
                                                self.hubItemClicked(controlID)
                                              File "/home/osmc/.kodi/addons/script.plex/lib/windows/home.py", line 521, in hubItemClicked
                                                controlID = 400 + self.hubFocusIndexes.index(idx)
                                            ValueError: tuple.index(x): x not in tuple
                                            -->End of Python script error report<--
22:27:09.020 T:4080611920   ERROR: Control 400 in window 13002 has been asked to focus, but it can't
22:46:22.875 T:4030722816   ERROR: Previous line repeats 10 times.
```

**Comment by pannal** [comment]
Didn't happen anymore with current develop, I'll reopen if it does. Thank you!
