### ISSUE TITLE
Cannot see shows on latest Kodi Leia RC1

### ISSUE THREAD

**Issue by dawesc** [plexinc/plex-for-kodi#262]
## Description:
For some (not all, but most) shows i get the following exception when pulling it up:

20:38:48.550 T:3555812208   ERROR: Traceback (most recent call last):
20:38:48.551 T:3555812208   ERROR:   File "/storage/.kodi/addons/script.plex/lib/_included_packages/plexnet/plexobjects.py", line 219, in reload
20:38:48.551 T:3555812208   ERROR:     data = self.server.query('/library/metadata/{0}'.format(self.ratingKey), params=kwargs)
20:38:48.552 T:3555812208   ERROR:   File "/storage/.kodi/addons/script.plex/lib/_included_packages/plexnet/plexserver.py", line 193, in query
20:38:48.552 T:3555812208   ERROR:     return ElementTree.fromstring(data) if data else None
20:38:48.552 T:3555812208   ERROR:   File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1311, in XML
20:38:48.552 T:3555812208   ERROR:   File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1659, in feed
20:38:48.552 T:3555812208   ERROR:   File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1523, in _raiseerror
20:38:48.552 T:3555812208   ERROR: ParseError: duplicate attribute: line 39, column 1056
20:38:48.975 T:3555812208   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: __call__() takes exactly 2 arguments (1 given)
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/script.plex/lib/windows/kodigui.py", line 101, in onInit
                                                self.onFirstInit()
                                              File "/storage/.kodi/addons/script.plex/lib/windows/busy.py", line 19, in inner
                                                return func(*args, **kwargs)
                                              File "/storage/.kodi/addons/script.plex/lib/windows/episodes.py", line 120, in onFirstInit
                                                self._setup()
                                              File "/storage/.kodi/addons/script.plex/lib/windows/episodes.py", line 148, in _setup
                                                self.updateProperties()
                                              File "/storage/.kodi/addons/script.plex/lib/windows/episodes.py", line 657, in updateProperties
                                                self.genre = self.show_.genres() and self.show_.genres()[0].tag or ''
                                            TypeError: __call__() takes exactly 2 arguments (1 given)
                                            -->End of Python script error report<--

## Details:
- Add-on version:
repo master and develop @ 1.7.a2 @ adcb590422d43ce7ae5a064bf197fdda0c1768dc
- Kodi version:
kodi-18.0rc1-Leia
- OS Platform:
LibreElec Master @49049575d7e1c7743dea3a3e55d7b6e4ae56c91e
- Hardware:
S905 (MXQ)

## Checklist
- [ ] I have included a link to a log (or at the very least a link to a forum post with a log) from a session that had the issue
- [ ] I have added appropriate GitHub labels

**Comment by pannal** [comment]
I don't have that issue with 18.2-RC1 (on OSMC). Maybe try [my develop branch](https://github.com/pannal/plex-for-kodi/tree/develop)?
