### ISSUE TITLE
Intermittent blank screen after playing a video

### ISSUE THREAD

**Issue by nonobio** [plexinc/plex-for-kodi#323]
Hello

## Description:

**Since some weeks, i have an intermittent issue when i play my personnal videos : sometimes i only have a blanck screen and i can only see my mouse pointer :**

![NUMEuE0](https://user-images.githubusercontent.com/7425799/86952674-a43b0880-c153-11ea-92d1-37c9e3bdafcd.png)

Sometimes i can solve my issue by clicking anywhere or pressing the enter key, but sometimes i have to kill Kodi…

**I tried to change some settings like :**

- Kodi setting “Adjust refresh rate” : from always to never
- Kodi setting “Use DXVA” : from yes to no
- Plex add-on setting “Use Direct Play” from yes to no
- Plex add-on setting “Use Direct Stream” from yes to no

**None helped.**

**I tried to analyse the kodi log with “debugging” activated;** i saw some lines with one of my add-on listed (betaseries) : i disabled it : same issue.

**This is an excerpt of my log when the issue occure** (but not sure if it is exactly the good time) :

`2020-07-06 11:26:18.039 T:7748  NOTICE: script.plex: API: GET https://192-168-1-2.52429062bf95480e9d5675be42cffd55.plex.direct:32400/library/sections/13/all?sort=viewUpdatedAt:desc&viewOffset>=300&viewUpdatedAt>=1584345334&X-Plex-Token=****
2020-07-06 11:26:18.039 T:8268  NOTICE: script.plex: BGThreader (queue.0:worker.3): Idle
2020-07-06 11:26:18.039 T:15540  NOTICE: script.plex: BGThreader (queue.0:worker.5): Idle
2020-07-06 11:26:18.039 T:14548  NOTICE: script.plex: BGThreader (queue.0:worker.6): Idle
2020-07-06 11:26:18.040 T:15656  NOTICE: script.plex: BGThreader (queue.0:worker.4): Idle
2020-07-06 11:26:18.040 T:4760  NOTICE: script.plex: API: GET https://192-168-1-2.52429062bf95480e9d5675be42cffd55.plex.direct:32400/hubs/home/onDeck?X-Plex-Token=****
2020-07-06 11:26:18.042 T:3032   DEBUG: [Warning] CGUITextureManager::GetTexturePath: could not find texture '-'
2020-07-06 11:26:18.048 T:11992   DEBUG: Previous line repeats 9 times.
2020-07-06 11:26:18.048 T:11992   DEBUG: ffmpeg[2ED8]: [swscaler] No accelerated colorspace conversion found from yuv420p to bgra.
2020-07-06 11:26:18.051 T:10660   DEBUG: ffmpeg[29A4]: [swscaler] No accelerated colorspace conversion found from yuv420p to bgra.
2020-07-06 11:26:18.102 T:3032   DEBUG: ------ Window Deinit (C:\Users\mbmc\AppData\Roaming\Kodi\addons\script.plex\resources\skins\Main\1080i\script-plex-seek_dialog.xml) ------
2020-07-06 11:26:18.103 T:3032   DEBUG: [Warning] CGUITextureManager::GetTexturePath: could not find texture '-'
2020-07-06 11:26:18.311 T:15972   DEBUG: ### [TV Time] - Position tracker ending with last_pos = 2.31100010872
2020-07-06 11:26:18.315 T:13148   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ZeroDivisionError'>
                                            Error Contents: float division by zero
                                            Traceback (most recent call last):
                                              File "C:\Users\mbmc\AppData\Roaming\Kodi\addons\script.tvtime\default.py", line 139, in onNotification
                                                actual_percent = (self._last_pos/self._total_time)*100
                                            ZeroDivisionError: float division by zero
                                            -->End of Python script error report<--
2020-07-06 11:26:18.319 T:15888  NOTICE: script.plex: Player: Idling...
2020-07-06 11:26:18.352 T:14384  NOTICE: script.plex: API: GET https://192-168-1-2.52429062bf95480e9d5675be42cffd55.plex.direct:32400/library/metadata/356596?X-Plex-Token=****
2020-07-06 11:26:18.419 T:15144  NOTICE: script.plex: BGThreader (queue.0:worker.0): Idle
2020-07-06 11:26:18.453 T:7748  NOTICE: script.plex: Hub video.inprogress.13 updated - refreshing section: u'    Vid\xe9os MBMC'
2020-07-06 11:26:18.469 T:7748  NOTICE: script.plex: HUB: video.inprogress.13 [video.inprogress](0)
2020-07-06 11:26:18.476 T:10660   DEBUG: ffmpeg[29A4]: [swscaler] No accelerated colorspace conversion found from yuv420p to bgra.
2020-07-06 11:26:18.486 T:7748  NOTICE: script.plex: BGThreader (queue.0:worker.1): Idle
2020-07-06 11:26:18.486 T:4760  NOTICE: script.plex: BGThreader (queue.0:worker.2): Idle
2020-07-06 11:26:18.491 T:1352   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: 'movie'
                                            Traceback (most recent call last):
                                              File "C:\Users\mbmc\AppData\Roaming\Kodi\addons\service.betaseries.com\betaseries.py", line 348, in onNotification
                                                scraper_data = json.loads(get_urldata(scraper_url,"","GET"))["movie"]
                                            KeyError: 'movie'
                                            -->End of Python script error report<--`

## Details:
- Add-on version: 0.2.1
- Kodi version: 18.7
- OS Platform: Windows 7
- Hardware: PC with motherboard Gigabyte Technology Co. Ltd. M68M-S2P (Socket M2), CPU AMD Phenom II X6 1035T, RAM 8.00 Go Canal-Double DDR2, GPU 1024 Mo ATI Radeon HD 4850 Series
-Plex server version : 1.19.4.2935-79e214ead

## Checklist
- [ ] I have included a link to a log (or at the very least a link to a forum post with a log) from a session that had the issue
- [ ] I have added appropriate GitHub labels

Thanks for your help

**Comment by pannal** [comment]
Could you try disabling betaseries.com and tvtime and see if the issue persists?

**Comment by nonobio** [comment]
Hello :)

I did already disabled betaseries and today i disabled TV Time too : same issue :(

I tried also to use "false" full screen : same issue...

Thanks

**Comment by pannal** [comment]
Can you please attach your log after you've disabled those two plugins and encountered the issue again? Also enabling debugging would help.

**Comment by nonobio** [comment]
Hi,

Done : [](https://paste.kodi.tv/ohopalecih.kodi)

What i did for this log :

-  I started Kodi

- disabled Betaseries and TV Time

- started Plex

- played a video (20160808150030) ( : the issue occurs at the end of the first play : grey screen with only mouse pointer.

- i pressed "OK" (a workaround i found yesterday ) : Plex GUI comed back.

- i leaved Plex add-on : grey screen again !

- i press "ECHAP" and Kodi GUI is displayed

- if i try to start Plex again : it donest' open

- Finally i quit Kodi

Thanks :)

**Comment by pannal** [comment]
Please check whether [my develop branches](https://github.com/pannal/plex-for-kodi) fix your issue.

**Comment by nonobio** [comment]
Hello,

Thanks. I installed versuib 0.1.7a3 from [https://github.com/pannal/plex-for-kodi/tree/develop_kodi18](https://github.com/pannal/plex-for-kodi/tree/develop_kodi18) and i have the same issue.

But i'm not sure it is the version you would i test ?

**Comment by pannal** [comment]
Yes it is, but make sure to disable automatic updates for the addon before installing it. Otherwise it can be overwritten by Kodi immediately.

**Comment by nonobio** [comment]
I just checked : it hasn't be updated while testing.

**Comment by pannal** [comment]
Do you have a current log with my branch running?

**Comment by nonobio** [comment]
Hello,

Here : [https://paste.kodi.tv/uzehalahoq.kodi](https://paste.kodi.tv/uzehalahoq.kodi)

Thanks :)

**Comment by pannal** [comment]
To help me narrow down where this might come from: Can you tell me what kind of media item this is in Plex? Does this happen only when using the mouse for control or also using the keyboard?

**Comment by nonobio** [comment]
Hi,

For the test i always use the smallest video i have, to quickly reach the end. This is the mediainfo of this video:

`General
Complete name               : D:\VIDEOS\Mes vidéos\Vidéos MBMC\2016.08\20160808150030.mp4
Format                      : MPEG-4
Format profile              : Base Media / Version 2
Codec ID                    : mp42 (mp42/avc1)
File size                   : 4.64 MiB
Duration                    : 2 s 880 ms
Overall bit rate mode       : Variable
Overall bit rate            : 13.5 Mb/s
Encoded date                : UTC 2016-08-08 15:00:30
Tagged date                 : UTC 2016-08-08 15:00:30
PANA                        : DMC-FT30

Video
ID                          : 1
Format                      : AVC
Format/Info                 : Advanced Video Codec
Format profile              : Baseline@L3.1
Format settings             : 2 Ref Frames
Format settings, CABAC      : No
Format settings, Reference  : 2 frames
Format settings, GOP        : M=1, N=6
Codec ID                    : avc1
Codec ID/Info               : Advanced Video Coding
Duration                    : 2 s 880 ms
Bit rate mode               : Variable
Bit rate                    : 11.4 Mb/s
Maximum bit rate            : 16.8 Mb/s
Width                       : 1 280 pixels
Height                      : 720 pixels
Display aspect ratio        : 16:9
Frame rate mode             : Constant
Frame rate                  : 25.000 FPS
Color space                 : YUV
Chroma subsampling          : 4:2:0
Bit depth                   : 8 bits
Scan type                   : Progressive
Bits/(Pixel*Frame)          : 0.494
Stream size                 : 3.91 MiB (84%)
Encoded date                : UTC 2016-08-08 15:00:30
Tagged date                 : UTC 2016-08-08 15:00:30
Color primaries             : BT.709
Transfer characteristics    : BT.709
Matrix coefficients         : BT.709
Codec configuration box     : avcC

Audio
ID                          : 2
Format                      : AAC LC
Format/Info                 : Advanced Audio Codec Low Complexity
Codec ID                    : mp4a-40-2
Duration                    : 2 s 880 ms
Bit rate mode               : Constant
Bit rate                    : 128 kb/s
Channel(s)                  : 2 channels
Channel layout              : L R
Sampling rate               : 48.0 kHz
Frame rate                  : 46.875 FPS (1024 SPF)
Compression mode            : Lossy
Stream size                 : 43.7 KiB (1%)
Encoded date                : UTC 2016-08-08 15:00:30
Tagged date                 : UTC 2016-08-08 15:00:30
`
I never use the mouse, only my keyboard or my remote control.

Thanks

**Comment by pannal** [comment]
How do you enter the video? From the home screen, from a playlist on the homescreen, from the library - can you give me the full steps?

**Comment by nonobio** [comment]
Hi,

Yes, so:

1- I launch Plex from main menu : add-ons : add-ons video : Plex
2- I go to "Vidéos MBMC" library on the top of Plex screen, with my keyboard : right arrow
3- I hit "Enter"
4- My vidéos are displayed as list (All movies) sorted by duration (smaller at the top)
5- The first video (the one i use to test) is selected, i hit enter
6- I arrive on the video selected screen with button "i", play", "settings" : the play button is select, i hit "Enter"
7- The video is played and i have the issue at the end.

Thanks
