### ISSUE TITLE
TypeError: 'filter' object is not subscriptable

### ISSUE THREAD

**Issue by fernandoalonzo** [plexinc/plex-for-kodi#325]
## Description:
TV Shows won't play due an error in `plexnet/video.py` line 461. Error log:
```
ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                Error Type: <class 'TypeError'>
                Error Contents: 'filter' object is not subscriptable
                Traceback (most recent call last):
                    File "/Users/kodi/Library/Application Support/Kodi/addons/script.plex/lib/windows/kodigui.py", line 105, in onInit
                    self.onFirstInit()
                    File "/Users/kodi/Library/Application Support/Kodi/addons/script.plex/lib/windows/videoplayer.py", line 91, in onFirstInit
                    self.play(resume=self.resume)
                    File "/Users/kodi/Library/Application Support/Kodi/addons/script.plex/lib/windows/videoplayer.py", line 234, in play
                    player.PLAYER.playVideoPlaylist(self.playQueue, resume=self.resume, session_id=id(self), handler=handler)
                    File "/Users/kodi/Library/Application Support/Kodi/addons/script.plex/lib/player.py", line 806, in playVideoPlaylist
                    self._playVideo(resume and self.video.viewOffset.asInt() or 0, seeking=handler and handler.SEEK_PLAYLIST or 0, force_update=True)
                    File "/Users/kodi/Library/Application Support/Kodi/addons/script.plex/lib/player.py", line 761, in _playVideo
                    self.handler.setup(self.video.duration.asInt(), offset, bifURL, title=self.video.grandparentTitle, title2=self.video.title, seeking=seeking)
                    File "/Users/kodi/Library/Application Support/Kodi/addons/script.plex/lib/player.py", line 169, in setup
                    self.getDialog(setup=True)
                    File "/Users/kodi/Library/Application Support/Kodi/addons/script.plex/lib/player.py", line 174, in getDialog
                    self.dialog = seekdialog.SeekDialog.create(show=False, handler=self)
                    File "/Users/kodi/Library/Application Support/Kodi/addons/script.plex/lib/windows/kodigui.py", line 44, in create
                    window = cls(cls.xmlFile, cls.path, cls.theme, cls.res, **kwargs)
                    File "/Users/kodi/Library/Application Support/Kodi/addons/script.plex/lib/windows/seekdialog.py", line 123, in __init__
                    self.intro = self.handler.player.video.intro
                    File "/Users/kodi/Library/Application Support/Kodi/addons/script.plex/lib/_included_packages/plexnet/video.py", line 461, in intro
                    self._intro = (filter(lambda x: x.type == "intro", self.markers) or [False])[0]
                TypeError: 'filter' object is not subscriptable
                -->End of Python script error report<--
```
In python3 [`filter()`](https://docs.python.org/3/library/functions.html#filter) receives an `iterable` and returns an `iterator`, hence [`next()`](https://docs.python.org/3/library/functions.html#next) must be used instead of `[0]` to access the first element of the resulting `iterator`. 

## Details:
- Add-on version:
0.3.1
- Kodi version:
Build: 19.0-ALPHA1 (18.9.701)
Git: 20200726-db40b2ade4
Python: 3.8.5
- OS Platform:
macOS Catalina 10.15.6
- Hardware:
Macbook Pro

## Checklist
- [x] I have included a link to a log (or at the very least a link to a forum post with a log) from a session that had the issue
- [ ] I have added appropriate GitHub labels

**Comment by pannal** [comment]
Please check whether [my develop branches](https://github.com/pannal/plex-for-kodi) fix your issue.
