### ISSUE TITLE
object has no attribute 'updateBackgroundFrom'

### ISSUE THREAD

**Issue by ZsBT** [plexinc/plex-for-kodi#390]
## Description:

BUG: AttributeError: 'PrePlayWindow' object has no attribute 'updateBackgroundFrom'

A couple of other Window classes drop the exception above.

## Details:
- Add-on version: 3
- Kodi version: 19
- OS Platform: debian bullseye
- Hardware: RPI 4

## Checklist
- [x] I have included a link to a log (or at the very least a link to a forum post with a log) from a session that had the issue
- [ ] I have added appropriate GitHub labels

```
2023-12-10 21:04:49.214 T:1482928   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: 'PrePlayWindow' object has no attribute 'updateBackgroundFrom'
                                                   Traceback (most recent call last):
                                                     File "/root/.kodi/addons/script.plexmod/lib/windows/kodigui.py", line 116, in onInit
                                                       else "ff000000"
                                                     File "/root/.kodi/addons/script.plexmod/lib/windows/preplay.py", line 105, in onReInit
                                                       self.refreshInfo(from_reinit=True)
                                                     File "/root/.kodi/addons/script.plexmod/lib/windows/preplay.py", line 113, in refreshInfo
                                                       self.setInfo(skip_bg=from_reinit and not (self.PLAY_BUTTON_ID <= oldFocusId <= self.MEDIA_BUTTON_ID))
                                                     File "/root/.kodi/addons/script.plexmod/lib/windows/preplay.py", line 509, in setInfo
                                                       self.updateBackgroundFrom(self.video)
                                                   AttributeError: 'PrePlayWindow' object has no attribute 'updateBackgroundFrom'
                                                   -->End of Python script error report<--
```

**Comment by ZsBT** [comment]
workaround patch:
```
--- a/lib/windows/windowutils.py
+++ b/lib/windows/windowutils.py
@@ -13,6 +13,9 @@ class UtilMixin():
     def __init__(self):
         self.exitCommand = None
 
+    def updateBackgroundFrom(self, obj):
+        return
+
     def goHome(self, section=None):
         HOME.show()
         if section:
```

**Comment by pannal** [comment]
You're in the wrong project. You're using my fork, PM4K. https://github.com/pannal/plex-for-kodi/
