### ISSUE TITLE
I cant re-sign-in (Pi2 - OSMC)

### ISSUE THREAD

**Issue by vampywiz17** [plexinc/plex-for-kodi#71]
Hello there,

First time, i able to sign-in, working everything well, but i need to reinstall my system. I tried login again, but get this:

21:24:45 417.368805 T:1541403632 ERROR: Exception in thread PIN-LOGIN:Token-Poll:
Traceback (most recent call last):
File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
self.run()
File "/usr/lib/python2.7/threading.py", line 763, in run
self.__target(*self.__args, **self.__kwargs)
File "/home/osmc/.kodi/addons/script.plex/lib/_included_packages/plexnet/myplex.py", line 48, in _poll
data = ElementTree.fromstring(response.text.encode('utf-8'))
File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1300, in XML
parser.feed(text)
File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
self._raiseerror(v)
File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
raise err
ParseError: syntax error: line 1, column 0

I try to reinstall, and restart, but get this every time.....

**Comment by ruuk** [comment]
It's happening to all clients right now. It's a server side issue.
