### ISSUE TITLE
PIN authentication page crashes

### ISSUE THREAD

**Issue by Enigma0** [plexinc/plex-for-kodi#85]
```
23:50:42.236 T:139999660662272 WARNING: JSONRPC: Could not parse type "Setting.Details.SettingList"
23:50:42.286 T:139999660662272  NOTICE: UpdateLibraries: Starting video library startup scan
23:50:42.294 T:139999660662272  NOTICE: initialize done
23:50:42.294 T:139999660662272  NOTICE: Running the application...
23:50:42.297 T:139999660662272  NOTICE: starting zeroconf publishing
23:50:42.297 T:139999660662272  NOTICE: starting upnp client
23:50:42.298 T:139997571163904  NOTICE: ES: Starting UDP Event server on port 9777
23:50:42.298 T:139997571163904  NOTICE: UDP: Listening on port 9777 (ipv6 : false)
23:50:42.372 T:139999171270400  NOTICE: VideoInfoScanner: Starting scan ..
23:50:42.376 T:139999171270400  NOTICE: VideoInfoScanner: Finished scan. Scanning for video info took 00:00
23:50:47.616 T:139997990602496 WARNING: CSkinInfo: failed to load skin settings
23:50:49.662 T:139998015780608 WARNING: Previous line repeats 3 times.
23:50:49.662 T:139998015780608   ERROR: Exception in thread PIN-LOGIN:Token-Poll:
                                            Traceback (most recent call last):
                                              File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
                                                self.run()
                                              File "/usr/lib/python2.7/threading.py", line 754, in run
                                                self.__target(*self.__args, **self.__kwargs)
                                              File "/home/[USER]/.kodi/addons/script.plex/lib/_included_packages/plexnet/myplex.py", line 45, in _poll
                                                response = http.GET(self.POLL.format(self.id))
                                              File "/home/[USER]/.kodi/addons/script.plex/lib/_included_packages/plexnet/http.py", line 27, in GET
                                                return requests.get(*args, headers=util.BASE_HEADERS.copy(), timeout=util.TIMEOUT, **kwargs)
                                              File "/home/[USER]/.kodi/addons/script.module.requests/lib/requests/api.py", line 70, in get
                                                return request('get', url, params=params, **kwargs)
                                              File "/home/[USER]/.kodi/addons/script.module.requests/lib/requests/api.py", line 56, in request
                                                return session.request(method=method, url=url, **kwargs)
                                              File "/home/[USER]/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 488, in request
                                                resp = self.send(prep, **send_kwargs)
                                              File "/home/[USER]/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 609, in send
                                                r = adapter.send(request, **kwargs)
                                              File "/home/[USER]/.kodi/addons/script.module.requests/lib/requests/adapters.py", line 497, in send
                                                raise SSLError(e, request=request)
                                            SSLError: ('bad handshake: SysCallError(0, None)',)
23:50:52.084 T:139997990602496 WARNING: CSkinInfo: failed to load skin settings
23:50:54.024 T:139998015780608 WARNING: Previous line repeats 3 times.
23:50:54.025 T:139998015780608   ERROR: Exception in thread PIN-LOGIN:Token-Poll:
                                            Traceback (most recent call last):
                                              File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
                                                self.run()
                                              File "/usr/lib/python2.7/threading.py", line 754, in run
                                                self.__target(*self.__args, **self.__kwargs)
                                              File "/home/[USER]/.kodi/addons/script.plex/lib/_included_packages/plexnet/myplex.py", line 45, in _poll
                                                response = http.GET(self.POLL.format(self.id))
                                              File "/home/[USER]/.kodi/addons/script.plex/lib/_included_packages/plexnet/http.py", line 27, in GET
                                                return requests.get(*args, headers=util.BASE_HEADERS.copy(), timeout=util.TIMEOUT, **kwargs)
                                              File "/home/[USER]/.kodi/addons/script.module.requests/lib/requests/api.py", line 70, in get
                                                return request('get', url, params=params, **kwargs)
                                              File "/home/[USER]/.kodi/addons/script.module.requests/lib/requests/api.py", line 56, in request
                                                return session.request(method=method, url=url, **kwargs)
                                              File "/home/[USER]/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 488, in request
                                                resp = self.send(prep, **send_kwargs)
                                              File "/home/[USER]/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 609, in send
                                                r = adapter.send(request, **kwargs)
                                              File "/home/[USER]/.kodi/addons/script.module.requests/lib/requests/adapters.py", line 497, in send
                                                raise SSLError(e, request=request)
                                            SSLError: ('bad handshake: SysCallError(0, None)',)
23:51:00.314 T:139997998995200   ERROR: GetDirectory - Error getting
23:51:00.496 T:139997990602496   ERROR: Previous line repeats 6 times.
```

**Comment by ruuk** [comment]
Looks like this is likely a temporary server issue. I can't duplicate it. Are you still getting this error?

In any case, I added handling for this sort of error so it doesn't crash when it happens. It will be in the next release.

**Comment by Enigma0** [comment]
@ruuk Yeah it's still happening. It sometimes gets a PIN and crashes immediately. Other times it says it cannot connect to plex.tv.

**Comment by Enigma0** [comment]
Still happening. Seems like at this point it might be an issue local to my system. I've recently deleted the `.kodi` folder and reinstalled from the stable PPA though so not sure what could be up.

**Comment by Enigma0** [comment]
Alright got it working...

`pip install cryptography` or `sudo -H pip install -U cryptography`
`pip install pyopenssl` or `sudo -H pip install -U pyopenssl`
`pip install -U pip` or `sudo -H pip install -U pip`
- http://forum.kodi.tv/showthread.php?tid=304441

`pip` seems to have sudo vs non-sudo issues.
